apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    severity: 10
    matchPaths:
      - path: /bin/sh
      - path: /bin/bash
    action: Block
  message: "Zero-trust policy violation: Attempted to execute an unauthorized shell."
