name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/wisecow-app:latest
          
      - name: Start Minikube with Ingress
        uses: medyagh/setup-minikube@latest
        with:
          addons: ingress

      - name: Install Cert-Manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.12.0 \
            --set installCRDs=true

      - name: Wait for Cert-Manager pods to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=cert-manager \
          --timeout=5m -n cert-manager

      - name: Apply Kubernetes Manifests
        run: |
          # The deployment order is important:
          # 1. Self-signed Issuer
          # 2. Deployment and Service
          # 3. Ingress with TLS
          kubectl apply -f k8s/issuer.yaml
          kubectl apply -f k8s/
